# Generated by Django 3.1.4 on 2021-01-12 12:47

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fastsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviseOrder',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', salesforce.fields.IntegerField(db_column='user_id__c')),
                ('status', salesforce.fields.CharField(choices=[('placed', 'placed'), ('shipped', 'shipped'), ('delivered', 'delivered')], db_column='status__c')),
                ('Product2Id', salesforce.fields.ForeignKey(db_column='Product2Id__c', on_delete=django.db.models.deletion.DO_NOTHING, to='fastsite.product')),
            ],
            options={
                'verbose_name': 'ReviseOrder',
                'verbose_name_plural': 'ReviseOrders',
                'db_table': 'ReviseOrder__c',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
