# Generated by Django 3.1.4 on 2020-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255, verbose_name='Product Name')),
                ('product_code', models.CharField(blank=True, db_column='ProductCode', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Product Description')),
                ('is_active', models.BooleanField(db_column='IsActive', default=False, verbose_name='Active')),
                ('family', models.CharField(blank=True, choices=[('None', 'None')], db_column='Family', max_length=255, null=True, verbose_name='Product Family')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
