# Generated by Django 3.1.4 on 2021-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=18),
            preserve_default=False,
        ),
    ]
