# Generated by Django 3.1.4 on 2021-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_product_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
